parameters:
    azure_blob_storage.storageAccountName     : '%env(AZURE_BLOB_STORAGE_STORAGE_ACCOUNT_NAME)%'
    azure_blob_storage.defaultEndpointProtocol: 'https'
    azure_blob_storage.containerName          : 'container-name-example'
    azure_active_directory.clientId           : '%env(AZURE_BLOB_STORAGE_CLIENT_ID)%'
    azure_active_directory.tenantId           : '%env(AZURE_BLOB_STORAGE_TENANT_ID)%'
    azure_active_directory.clientSecret       : '%env(AZURE_BLOB_STORAGE_CLIENT_SECRET)%'
    
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: fals

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\CacheRegistry:
        class: App\Service\CacheRegistry
        public: true
        arguments:
            - '%redis_host%'
            - 'cache_'
            - '%redis_password%'
            - '%redis_port%'

    App\Service\UploadCache:
        class: App\Service\UploadCache
        public: true
        arguments:
            - '@App\Service\CacheRegistry'
            - 1200 # 20 minutes in seconds.

    App\Service\BlobStorageManager:
        class: App\Service\BlobStorageManager
        public: true
        arguments:
            - '@App\Service\BlobStorageAuthenticator'
            - '%containerName%'
            - '@kernel'

    App\Service\BlobStorageAuthenticator:
        class: App\Service\BlobStorageAuthenticator
        public: true
        arguments:
            - '%storageAccountName%'
            - '%defaultEndpointProtocol%'
            - '@App\Service\UploadCache'
            - '%clientId%'
            - '%tenantId%'
            - '%clientSecret%'
