parameters:
    storageAccountName     : 'testsignature'
    defaultEndpointProtocol: 'https'
    containerName          : 'container-example'
    clientId           : '5b7a2a0a-042e-4d69-8088-53fcf5e9605a'
    tenantId           : 'a84cd936-3cb4-4d07-b1d5-a93d8a5eab56'
    clientSecret       : '-_48Q~BY4sqatQEbXhwUwfzjpYnGCVxp09Elxb-Q'
    
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: fals

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\CacheRegistry:
        class: App\Service\CacheRegistry
        public: true
        arguments:
            - '%redis_host%'
            - 'cache_'
            - '%redis_password%'
            - '%redis_port%'

    App\Service\UploadCache:
        class: App\Service\UploadCache
        public: true
        arguments:
            - '@App\Service\CacheRegistry'
            - 1200 # 20 minutes in seconds.

    App\Service\BlobStorageManager:
        class: App\Service\BlobStorageManager
        public: true
        arguments:
            - '@App\Service\BlobStorageAuthenticator'
            - '%containerName%'
            - '@kernel'

    App\Service\BlobStorageAuthenticator:
        class: App\Service\BlobStorageAuthenticator
        public: true
        arguments:
            - '%storageAccountName%'
            - '%defaultEndpointProtocol%'
            - '@App\Service\UploadCache'
            - '%clientId%'
            - '%tenantId%'
            - '%clientSecret%'
